# ===================================
#  Form Behavior Config
# ===================================

name: xinix.blog::lang.blog.create_category
form: ~/plugins/xinix/blog/models/category/fields.yaml
modelClass: Xinix\Blog\Models\Category
defaultRedirect: xinix/blog/categories

create:
    redirect: xinix/blog/categories/update/:id
    redirectClose: xinix/blog/categories

update:
    redirect: xinix/blog/categories
    redirectClose: xinix/blog/categories
