# ===================================
#  Form Behavior Config
# ===================================

name: xinix.blog::lang.blog.create_post
form: ~/plugins/xinix/blog/models/post/fields.yaml
modelClass: Xinix\Blog\Models\Post
defaultRedirect: xinix/blog/posts

create:
    redirect: xinix/blog/posts/update/:id
    redirectClose: xinix/blog/posts

update:
    redirect: xinix/blog/posts
    redirectClose: xinix/blog/posts
