# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/xinix/blog/models/game/columns.yaml

# Model Class name
modelClass: Xinix\Blog\Models\Game

# List Title
title: xinix.blog::lang.games.list_title

# Link URL for each record
recordUrl: xinix/blog/games/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 5

# Display checkboxes next to each record
showCheckboxes: true

showTree: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



